### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by rnalrd** [asipto/secsipidx#1]
Hi,

any chance that a release could be tagged? It would help in packaging. :smile: 

Thanks!

**Comment by miconda** [comment]
Hello, took me a little bit to tag a release, as I wanted to see if anyone reports issues. As I got a confirmation of successful interop testing, I just created branch 1.0 to track 1.0.x releases and tagged the v1.0.0 release.

If you work on packaging it for some distros, you can contribute the spec files to be included in this repo. Thanks!
