### ISSUE TITLE
Unable to verify via HTTP

### ISSUE THREAD

**Issue by steventwheeler** [asipto/secsipidx#12]
Hello,
I am attempting to run this application in HTTP mode. Whenever I try to verify identity headers, either received from a peer or generated myself, I get the following error message and the HTTP response body is `FAILED`.
```
failed checking identity: x509: certificate signed by unknown authority
```

I am using a certificate signed by TransNexus, specifically this CA root.
```
-----BEGIN CERTIFICATE-----
MIICDDCCAbKgAwIBAgIQZHuQ8Gzph59r9srK4FVowDAKBggqhkjOPQQDAjBmMQsw
CQYDVQQGEwJVUzETMBEGA1UEChMKVHJhbnNOZXh1czEiMCAGA1UECxMZQ2VydGlm
aWNhdGlvbiBBdXRob3JpdGllczEeMBwGA1UEAxMVVHJhbnNOZXh1cyBSb290IENB
IEcyMB4XDTIwMTEwNDAwMDAwMFoXDTQ1MTEwMzIzNTk1OVowZjELMAkGA1UEBhMC
VVMxEzARBgNVBAoTClRyYW5zTmV4dXMxIjAgBgNVBAsTGUNlcnRpZmljYXRpb24g
QXV0aG9yaXRpZXMxHjAcBgNVBAMTFVRyYW5zTmV4dXMgUm9vdCBDQSBHMjBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABORFCjUfX81JXNcMFSzpofTJsm9MAOMUxDlz
/aDK9vzjiZflUkdZA9Z1gveSck5PmyMxmIiOJ2TSw96bnOj96oejQjBAMA8GA1Ud
EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBR3nV+xPvo9U2Xf
rVgBRvG0bmJmtjAKBggqhkjOPQQDAgNIADBFAiAeMOsGifTYQl8tbQTbns8q50Qv
2Bi3KgLvJDBFjEOCdwIhAOd2Eh5v3oxQvjoTOrhPAT1FXeD34v+rL7idL4LBkkgh
-----END CERTIFICATE-----
```

This is the command I am running to start the HTTP server.
```
secsipidx -http-srv :8090 -cache-dir /secsipidx/cache -http-dir /secsipidx/public -timeout 3 -fprvkey /secsipidx/keys/private.pem -expire 3600 -ca-file /secsipidx/certs/ca-root-certs.pem -crl-file /secsipidx/certs/crl.pem -cert-verify 23
```

I can see that the public certificate is being downloaded and cached in `/secsipidx/cache` and `/secsipidx/certs/ca-root-certs.pem` contains all of the CA root certificates obtained from the STI-PA API. I even tried clearing out the file and including only the CA root used to sign the public certificate but that had no effect.

Any idea what I'm doing wrong? Or are there any other troubleshooting steps I should try?

**Comment by miconda** [comment]
If you disable certification verification (no `-cert-verify` or set to `0`), is returning success?

Just to rule out if it is related only to that part of code or something else fails as well, as I didn't get a chance to play with certificates signed by CAs, the implementation was done based on Go docs.

**Comment by steventwheeler** [comment]
Yes, if I disable verification entirely by setting `-cert-verify` to `0` then I get a successful response. I'm not too familiar with go, but I am willing to try tweaking it if you can point me in the right direction.

**Comment by miconda** [comment]
I haven't done really much with Go either, I looked around to figure out a solution how to verify certificates. The corresponding snippet of code for CA validation is:

  * https://github.com/asipto/secsipidx/blob/main/secsipid/secsipid.go#L226-L284
