### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by steve-kaufman** [asipto/secsipidx#15]
Hello!

Someone told me I should try adding support for div headers, but I got sidetracked and started adding regression tests instead.

So far, I've added unit tests for the `SJWTPubKeyVerify()` function. No compatibility breaks or anything, although I did make a slight adjustment to how it pulls the system CA pool so that it could be testable (and the exact reasoning is described thoroughly in comments).

I also went ahead and added testing CI with GitHub actions, so it should make it nice and easy to check if anything's broken when a change is made.

I was thinking regression tests might also lay some groundwork for a more modular refactor, if you're so inclined.

I did also add a `go.mod`, which certainly isn't necessary for the changes made but does make development about 1000x easier and shouldn't break anything, to my knowledge.

**Comment by steve-kaufman** [comment]
**Update:** Unit tests for `SJWTParseECPrivateKeyFromPEM()`  and `SJWTParseECPublicKeyFromPEM()` have been added.

**Comment by miconda** [comment]
Thanks again for these contributions, the PR was merged. You are welcome to work on more modular refactor, I do not spend much time with Go language in my daily activity, for sure there are better approaches in many cases than what I did.

If the changes affect the way the lib and cli tool have to be build, please update the README.md to reflect it.
