### ISSUE TITLE
Redundancy in signing algorithm?

### ISSUE THREAD

**Issue by steve-kaufman** [asipto/secsipidx#17]
Hi again,

I'm trying to make some sense of the signing algorithm in `SJWTSignWithPrvKey()`, and it looks like there's a redundant bit here:

```golang
// Near the top:
// var sES256KeyBits = 256
//...
func SJWTSignWithPrvKey(...) {
    //...
    if sES256KeyBits != curveBits {
	return "", SJWTRetErrJSONSignatureSize, errors.New("invalid key size")
    }
    
    keyBytes := curveBits / 8
    if curveBits%8 > 0 {
	keyBytes++
    }
    //...
}
```

The statement: `if curveBits%8 > 0` should never be true, since it's been guaranteed that `curveBits` equals `256` in the lines above. Am I missing something here, or is this something redundant that just hasn't been removed yet?

There's a fair bit of nitty-gritty low-level mathy stuff going on in this function, so I want to make sure I've got it all straight. 
I probably ought to read up on ECDSA signing to understand exactly why it's being put together this way, but any input you have on that would be helpful.

(I'm mostly just curious and probably won't put in a PR that changes this for a while though)

**Comment by miconda** [comment]
Indeed, looks like the check is redundant. I put together the code from different sources (iirc, I looked at various golang jwt libraries) -- being my first touch of ECDSA signing, it might not be the most coherent checking/conditions around.

**Comment by miconda** [comment]
Closing it due to ageing, if someone thinks it is better without the extra check, then just make a PR.
