### ISSUE TITLE
Debian 10/Go 1.11: cannot find package "io/fs"

### ISSUE THREAD

**Issue by miconda** [asipto/secsipidx#19]
The latest version of `secsipid` makes use of `io/fs` packages, which was introduced in a recent version (likely first in `go 1.16`). Some stable Linux distros ship older Golang version.

For now checkout the version before using `io/fs`:

```
go get -d github.com/asipto/secsipidx
cd $GOPATH/src/asipto/secsipidx
git checkout bbac5944829d4ae286a26d4723c57a6bf7c595c9
make
make install
```

**Comment by jbowen7** [comment]
CentOS 8.4 is one of those distros.

Thanks for opening @miconda

**Comment by miconda** [comment]
@jbowen7 - there were couple of commits/PRs by @steve-kaufman I merged recently that introduced this dependency, they look good for the future.

I discover the issue with older Golang version as I did a new deploy but I didn't have the time to look for a solution that could cope with older and newer Golang versions. I may create a branch to deal with different Golang versions.

**Comment by jbowen7** [comment]
I understand.
I discovered it the same way.
If I find a solution I'll produce a PR.

**Comment by miconda** [comment]
Closing this one due to long time without an update The Go language is at v1.19.x and can be installed from provided binaries easily on Linux distros. If someone wants to still work on this, then just make a PR when having a patch.
