### ISSUE TITLE
Problem loadmodule secsipid on kamailio 5.6.5

### ISSUE THREAD

**Issue by sondesbough** [asipto/secsipidx#28]
May 24 11:26:36 vps-3471ad99 kamailio: ERROR: <core> [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_add_identity (params 6)
May 24 11:26:36 vps-3471ad99 kamailio: CRITICAL: <core> [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 802, column 125: unknown command, missing loadmodule?#012
May 24 11:26:36 vps-3471ad99 kamailio: INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Control process exited, code=exited, status=255/EXCEPTION
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Failed with result 'exit-code'.
May 24 11:26:36 vps-3471ad99 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Scheduled restart job, restart counter is at 2.
May 24 11:26:36 vps-3471ad99 systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:36 vps-3471ad99 systemd[1]: Starting Kamailio (OpenSER) - the Open Source SIP Server...
May 24 11:26:36 vps-3471ad99 kamailio: ERROR: <core> [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_build_identity (params 6)
May 24 11:26:36 vps-3471ad99 kamailio: CRITICAL: <core> [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 799, column 125: unknown command, missing loadmodule?#012
May 24 11:26:36 vps-3471ad99 kamailio: ERROR: <core> [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_add_identity (params 6)
May 24 11:26:36 vps-3471ad99 kamailio: CRITICAL: <core> [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 802, column 125: unknown command, missing loadmodule?#012
May 24 11:26:36 vps-3471ad99 kamailio[70519]: ERROR: bad config file (2 errors)
May 24 11:26:36 vps-3471ad99 kamailio: INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Control process exited, code=exited, status=255/EXCEPTION
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Failed with result 'exit-code'.
May 24 11:26:36 vps-3471ad99 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Scheduled restart job, restart counter is at 3.
May 24 11:26:36 vps-3471ad99 systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:36 vps-3471ad99 systemd[1]: Starting Kamailio (OpenSER) - the Open Source SIP Server...
May 24 11:26:36 vps-3471ad99 kamailio: ERROR: <core> [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_build_identity (params 6)
May 24 11:26:36 vps-3471ad99 kamailio: CRITICAL: <core> [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 799, column 125: unknown command, missing loadmodule?#012
May 24 11:26:36 vps-3471ad99 kamailio: ERROR: <core> [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_add_identity (params 6)
May 24 11:26:36 vps-3471ad99 kamailio[70521]: ERROR: bad config file (2 errors)
May 24 11:26:36 vps-3471ad99 kamailio: CRITICAL: <core> [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 802, column 125: unknown command, missing loadmodule?#012
May 24 11:26:36 vps-3471ad99 kamailio: INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Control process exited, code=exited, status=255/EXCEPTION
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Failed with result 'exit-code'.
May 24 11:26:36 vps-3471ad99 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:37 vps-3471ad99 systemd[1]: kamailio.service: Scheduled restart job, restart counter is at 4.
May 24 11:26:37 vps-3471ad99 systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:37 vps-3471ad99 systemd[1]: Starting Kamailio (OpenSER) - the Open Source SIP Server...
May 24 11:26:37 vps-3471ad99 kamailio: ERROR: <core> [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_build_identity (params 6)
May 24 11:26:37 vps-3471ad99 kamailio: CRITICAL: <core> [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 799, column 125: unknown command, missing loadmodule?#012
May 24 11:26:37 vps-3471ad99 kamailio[70522]: ERROR: bad config file (2 errors)
May 24 11:26:37 vps-3471ad99 kamailio: ERROR: <core> [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_add_identity (params 6)
May 24 11:26:37 vps-3471ad99 kamailio: CRITICAL: <core> [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 802, column 125: unknown command, missing loadmodule?#012

**Comment by miconda** [comment]
Duplicate #29.
